<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>RollingPotato</title>
	<!-- favicon -->
	<!-- link rel="shortcut icon" href="images/icons/favicon.ico" -->
	<!-- Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:500|Source+Code+Pro:300,400,600,700" rel="stylesheet">
	<!-- bootstrap -->
	<link rel="stylesheet" href="/resources/vendor/bootstrap/css/bootstrap.min.css">
	<!-- custom main stylesheet -->
	<link rel="stylesheet" href="/resources/css/creative.css">
</head>
<body>

	<section id="terms" class="section">
		<div class="container">
			<div class="row">
				<div class="about__text col-xs-12 col-md-12">
          <a href="/main.do#contact" rel="nofollow" class="text__button">Go to homepage</a>
					<h2 class="text__header">Terms and Conditions</h2>
					<p class="text__par">
            1. Objective of Standard Terms and Conditions<br>The objective of the Standard Terms and Conditions is to determine the provisions for the MARCOnPOLO (“MARCOnPOLO” or the “Company”) and Users’ rights, duties, and responsibilities in using the website provided by the Company (the “Service”). The Standard Terms and Conditions shall apply mutatis mutandis to electronic transactions using cable/wireless PC internet, smartphone (i-Phone and android phones, etc.) applications and mobile web, etc. unless contrary to their intrinsic characteristics.<br><!--[if !supportEmptyParas]-->
<!--[endif]--><br><!--[if !supportEmptyParas]-->
<!--[endif]--><br>2. Definition<br>① “Company” refers to MARCOnPOLO. It can also refer to a virtual workplace such as website, smartphone application, and mobile web, etc. established for the purpose of providing PlayPlanet’s goods or services to its Users<br>② “User” refers to Members and non-Members that access the Company and receive the Service provided by the Company pursuant to the Standard Terms and Conditions.<br>③ “Member” refers to any person who accesses the Company's "Service" and enters into a contract with the Company in accordance with the starndard Terms and Conditions and uses the Services provided by the Company.<br>④ “Account” refers to the email address provided by the Member and authorized by the Company or the account that is registered with another designated by the Company for the identification of members and use of the Service.<br>⑤ "Password" refers to the combination of English letters and numbers registered by the member himself / herself for the purpose of identifying the identity of the member and protecting the interests and confidentiality of the member.<br>⑥ “MARCO” refers to any Member who has access to the Company’s Service and is able to use the trip registered by POLO.<br>⑦ “POLO” refers to a member who registers a trip with the Company and provides guidance and experience to MARCO who purchased the relevant trip.<br>⑧ “Travel” refers to a conduct of POLO providing guidance and experience to MARCO in a region visited by MARCO.<br>⑨ “Post” refers to individual content such as travel, text, tags, links, photos, videos and various files registered on “MARCOnPOLO” when Member uses our service.<br><!--[if !supportEmptyParas]-->
<!--[endif]--><br><!--[if !supportEmptyParas]-->
<!--[endif]--><br>3. Display and Amendment of Standard Terms and Conditions<br>① The Company shall display the contents of the Standard Terms and Conditions on the first service page (front page) of the website so that the Users can easily find (provided, however, the contents of Standard Terms and Conditions shall be placed so that the Users can view on a linked screen).<br>② The Company may amend the Standard Terms and Conditions to the extent that it does not violate the relevant laws and regulations such as the Regulation of Standard Terms and Conditions Act, the Act on Promotion of Information and Communications Network Utilization and Information Protection, etc..<br>③ Where the Company amends the Standard Terms and Conditions, the Company shall prepare the current Standard Terms and Conditions, the amended Standard Terms and Conditions, the date of amendment, and the reasons for amendment and display them from 7 days prior to the amendment date to the date immediately preceding the amendment date.<br>④ Where the Member continues to use the Company’s Service after the announced date of amendment, the Member shall be presumed to have consented to the amended Standard Terms and Conditions. Any Member that does not consent to the amended Standard Terms and Conditions may terminate the Service Contract anytime at will.<br>⑤ The company may have a Terms of Service and separate operating policies for the services. Any matters undecided in the Standard Terms and Conditions shall follow the separate operating policies, other relevant laws or regulations or commercial practice.<br><!--[if !supportEmptyParas]-->
<!--[endif]--><br><!--[if !supportEmptyParas]-->
<!--[endif]--><br>4. Contract for Use<br>① The contract is concluded when the person who intends to become a “Member“(hereinafter referred to as ”applicant“) agrees with the contents of the agreement and applies for membership according to the method provided by the Company and the Company agrees with the application.<br>② The Company shall accept the application of the applicant for membership in principle. However, the Company may not approve or cancel the contract for use following applications.<br>1) The applicant has previously lost his / her membership in accordance with these Terms and Conditions. However, exceptions may be made if the member's approval of re-entry of the Company is obtained;<br>2) Where there is a stealing other person’s personal information, or a false, omitted, or erroneous detail in the registered information;<br>3) If a minor under the age of 17 has not obtained the consent of a legal reperesentative (parent, etc.);<br>4) Where there is an intention to use the Service for the purpose of fraudulent use or for profit;<br>5) Where the User subscribed for a purpose in breach of the relevant laws and regulations or a purpose of defeating the social custom;<br>6) Where there are insufficient facilities or technological obstacles for the Company’s operation of Service;<br>7) Any other violation of these Terms of Use, illegal or unauthorized use, or if the Company decides that it is necessary to refuse the application or terminate the contract of use by the reasonable judgment<br>③ The time of establishment of the contract of use is when the consent of the "Company" reaches the member.<br>④ The Company may classify members by grade according to company policy, and differentiate them by subdividing usage time, number of uses and service menu.<br><!--[if !supportEmptyParas]-->
<!--[endif]--><br><!--[if !supportEmptyParas]-->
<!--[endif]--><br>5. Change of member’s information<br>① "Member" must notify the change to the "Company" by correcting personal information online or by e-mail if there is any change in the contents created at the time of the contract of use.<br>② The Company shall not be held responsible for any disadvantages caused by not notifying the Company of any changes in Article 5 ①.<br><!--[if !supportEmptyParas]-->
<!--[endif]--><br><!--[if !supportEmptyParas]-->
<!--[endif]--><br>6. Termination of Contract of Use<br>① Members may ask to terminate their use agreement at any time by notifying the Company of their cancellation.<br>② The contract of use ends when the "Company" receives the intention to terminate the membership and terminates the processing.<br>③ Upon termination of the "Membership", all data of "Member" will be terminated immediately upon termination, unless the "Company" holds the member information in accordance with the related laws and the personal information processing policy.<br>④ The "Company" may restrict the use of the "Service" by warning, pausing or permanently stopping if "Member" violates the obligations of this Agreement or interferes with the operation of the Service.<br>⑤ In case of the following conducts, the "Company" may restrict membership or terminate the contract of use. If the "Company" is damaged by this, the relevant member must compensate the Company’s losses.<br>1) Where the Member registers false details at the time of membership application;<br>2) Where the Member threatens the order of electronic commercial transaction by obstructing other Member’s use or misusing other Member’s detail, etc.;<br>3) Where the Member, using the Company, commits a conduct that is prohibited by law or the Standard Terms and Conditions or contrary to the public order;<br>4) Where the Member misuses or collects other person’s information;<br>5) Where the Member conducts business activities using the Service without the Company’s prior written consent;<br>6) Where the Member transfers, leases, or otherwise offers as security to other parties the rights to use the Services or any other contractual status with the Company;<br>7) Where the Member reproduces the information acquired through the Service for purposes other than the use of Service, uses the said information in publications and broadcasting, etc. or provides to third parties without the Company’s prior consent;<br>8) Where the Member distributes insulting or defamatory contents or coarse and obscene information that is contrary to the public order;<br>9) Where the Member ridicules or threatens other User or constantly inflicts pain or inconvenience to a particular User; or<br>10) Where the Member commits a conduct that is in breach of the provisions specified in the Standard Terms and Conditions.<br>⑥ The member is responsible for the damages incurred by the termination of the contract of use, and the company is not responsible for any liability.<br><!--[if !supportEmptyParas]-->
<!--[endif]--><br><!--[if !supportEmptyParas]-->
<!--[endif]--><br>7. Notification to Members<br>① Where the Company intends to notify the Members, it may notify via the email address and SMS that the Members registered with the Company.<br>② Where the Company intends to notify unspecified masses of Members, the Company may substitute the individual notices with a posting of notice on the Company’s message board for 1 week or longer.<br><!--[if !supportEmptyParas]-->
<!--[endif]--><br><!--[if !supportEmptyParas]-->
<!--[endif]--><br>8. Duty of the Company<br>① The Company shall not commit a conduct that is prohibited under law and the Standard Terms and Conditions or contrary to the public order. The Company shall exercise its best efforts to provide the Service in a constant and stable manner pursuant to the Standard Terms and Conditions.<br>② The Company shall be equipped with a security system for the purpose of protection of User’s personal information so that the User can safely use the Service.<br><!--[if !supportEmptyParas]-->
<!--[endif]--><br><!--[if !supportEmptyParas]-->
<!--[endif]--><br>9. Duty over Members’ Personal Information<br>The terms and conditions under the Company’s Personal Information Protection Policy shall be applicable.<br><!--[if !supportEmptyParas]-->
<!--[endif]--><br><!--[if !supportEmptyParas]-->
<!--[endif]--><br>10. Duty over Members’ Account and Password<br>① Members are responsible for the management of accounts and passwords referred to in Paragraph 3 and 4 of Article 2 and Members are responsible for any civil or criminal liability that they may incur as a result of neglect.<br>② The Member shall not cause his/her ID and password to be used by third parties.<br>③ Where the Member loses his/her ID and password or recognizes that his/her ID and password is being used by third parties, he/she shall immediately notify the Company, and if the Company provides guidance, he/she shall follow such guidance.<br>④ Members are responsible for all disadvantages that may arise from failure to provide notice or to comply with the Company's actions pursuant to Section 3.<br><!--[if !supportEmptyParas]-->
<!--[endif]--><br><!--[if !supportEmptyParas]-->
<!--[endif]--><br>11. Duty of the Member<br>① "Member" shall comply with the Company's notices, such as related laws, regulations and guidelines, and shall not infringe on the rights of others or interfere with the work of the Company.<br>② "Member" shall not engage in any of the following conducts in connection with the use of the Service.<br>1) Registration of false contents when applying for or changing the contract of use;<br>2) To use the information posted on the company's service or the information obtained by the member using the service for the purpose of commercial, non-profit, reproduction, publication, broadcasting, etc. or providing it to a third party without prior consent of the company;<br>3) Unauthorized changes to company published information<br>4) Receiving money by means of services provided by the Company, such as by publicity of the person or a third party;<br>5) Transmitting or posting information (such as a computer program) or linking to related sites other than information set by the Company;<br>6) Infringement of intellectual property rights such as copyrights of the Company and other third parties;<br>7) To impair the reputation of the Company or any other third party or to disrupt business;<br>8) Publishing or posting on the Service, or distributing to the Company or its members any junk mail, spam, lucky mail, advertising mail, obscene or violent text, pictures, sound, videos;<br>9) Conduct in dealing directly with a polo and a third party for all travel products that are known through the intermediation of the "Company";<br>10) Acting to trade goods and services whose transactions are restricted according to the law<br>11) Conduct in posting or sending a message or an e-mail by impersonating the employee or service manager of the company or stealing the name of another person;<br>12) Interfering with the use of other members' services such as stalking, profanity, chatting, etc.;<br>13) To collect, store, disclose and disseminate the personal information of other members without consent;<br>14) To defame the reputation or credit of a company without grounds;<br>③ “MARCO“ agrees to the following duties.<br>1) “MARCO“ shall comply with the conditions and provisions designated by “POLO“<br>2) “MARCO“ shall not compel POLO and other MARCOs about commercial or religious matters.<br>3) MARCO shall not disclose to other Users the personal information of POLO received after making a reservation for Travel.<br>④ “POLO“ agrees to the following duties.<br>1) Polo shall precisely explain and lawfully proceed with Travel to be registered.<br>2) Polo agrees to the use of personal information for the Company’s activities.<br>3) Polo 0shall agree to the Company advertising all of the submitted Travels by various methods under the Company’s discretion.<br><!--[if !supportEmptyParas]-->
<!--[endif]--><br><!--[if !supportEmptyParas]-->
<!--[endif]--><br>12. Provision of “Services”<br>① The Company provides the following services to its members.<br>1) Provides functions for Polo to register for travel.<br>2) Provide Marco with information on travel, goods or services registered by Polo<br>3) Information of a contract between Marco and Polo<br>4) Any other service that the "Company" may further develop or provide to "Members" through partnership agreements with other companies<br>② The "Company" provides only the tools to enhance the reliability and stability of Marco and Polo transactions, while the responsibility of the "Polo" and "Marco" parties themselves is borne by the parties to the contracts established between them.<br>③ "Company" may charge service fee.<br>④ "Company" may change the contents of goods or services to be provided by contracts to be concluded in the event of a change in stocks or technical specifications of goods or services. In this case, we will notify the contents of the changed goods or services and the date of delivery to the place where the contents of the current goods or services are posted.<br>⑤ The "Company" may entrust a third party, such as an affiliate, with a portion of the Services, as deemed necessary.<br><!--[if !supportEmptyParas]-->
<!--[endif]--><br><!--[if !supportEmptyParas]-->
<!--[endif]--><br>13. Suspension of Service<br>① "Service" is provided 24 hours a day, seven days a week.<br>② "Company" may temporarily suspend the provision of "Services" in case of repair and maintenance, replacement and malfunctioning of IT facilities such as computer, interruption of communication, excessive use of services, national emergency, power failure, natural disaster, or operational reasons .<br>③ Where the Company is unable to provide the Service due to the reasons such as conversion of business type, withdrawal of business, or merger between companies, the Company shall notify the Users via the methods under Article 7 and compensate the Users pursuant to the terms and conditions originally offered by the Company.<br><!--[if !supportEmptyParas]-->
<!--[endif]--><br><!--[if !supportEmptyParas]-->
<!--[endif]--><br>14. Provision of Information and Display of Advertisements<br>① The Company may provide to the Members various information that are deemed necessary for the Members during the use of Service via announcement, email, post mail, SMS, Push Notification Message or phone, etc. Provided, however, the Member may refuse to receive email, etc. at anytime except transaction-related details under the relevant laws and regulations and responses to customer inquiries, etc.<br>② The Company may display advertisements in relation to the operation of Service on the Service screen, website, and emails. The Member that receives emails with advertisement may indicate his/her refusal to receive such emails.<br>③ "Company" shall not be liable for any loss or damage caused by the participation, communication or transaction of the user with the advertiser's promotional activities posted on the service or through the service.<br><!--[if !supportEmptyParas]-->
<!--[endif]--><br><!--[if !supportEmptyParas]-->
<!--[endif]--><br>15. Attribution of Company’s Copyright and Restriction of Use<br>① The copyright and intellectual property rights of the work created by "Service" and "Company" belong to "Company". However, we exclude "posts" from "members" and any works provided under the partnership agreement.<br>② With respect to the information for which the intellectual property right belongs to the Company amongst the information that the User acquired during the use of the Company, the User shall not reproduce, transmit, publish, distribute, broadcast, or use by other methods or cause third parties to use without the Company’s prior consent.<br>③ The "Company" only grants the Member a right to use the "Account", the Content, and the "Points" in accordance with the terms and conditions set by the "Company" and "Member" shall not be entitled to transfer, sell, nor provide any collateral.<br><!--[if !supportEmptyParas]-->
<!--[endif]--><br><!--[if !supportEmptyParas]-->
<!--[endif]--><br>16. Copyright and Management of User’s Post<br>① The copyright of the "post" posted by "member" in the "service" shall belong to the member who posted it, unless it violates the rights of the third party.<br>② In the event of damages or other problems arising from the "posts" of "members", "members" shall be liable for them, and "Company" shall not be held responsible.<br>③ 3. The "Company" may freely use the member's posts in a global scope or assign the post to a third party without the member's permission for the purpose of operating, exhibiting, and promoting the service. Within the scope, "posts" may be modified, duplicated, edited and published. It is also valid if the member terminates the contract. However, in this case, the company complies with the copyright law, and the "member" can request the deletion and the confidentiality of the post at any time.<br>④ If the "post" of the "member" includes contents that are in violation of relevant laws such as "Information and Communication Network Act" and "Copyright Act", the right holder may ask for the suspension and deletion of the relevant "post" in accordance with procedures established by relevant laws, and the "company" must take action in accordance with relevant laws.<br>⑤ "Company" may take temporary actions against such "post" in accordance with the relevant law if there is a reason to be recognized for infringement even if there is no request by the right holder pursuant to the preceding paragraph, or if it is in violation of company policies and related laws.<br>⑥ "Company" may take appropriate measures such as suspension, correction, deletion, movement or denial of registration without prior consent of the user in the following cases.<br>1) Where the Post seriously insults or defames another User or third parties;<br>2) Where the Post distributes or links to contents that are in violation of public order and social customs;<br>3) Where the Post incites illegal reproduction or hacking;<br>4) Where the Post advertises for the purpose of profit;<br>5) Where the Post contains a content that is related to crime from an objective point of view;<br>6)　Where the Post is in violation of the rules for Posts provided by the Company or inconsistent with the characteristics of posting board;<br>7）Where the Post contains political judgments or religious views and the Company determines that it is inconsistent with the characteristics of Service;　<br>⑦　Posts will not be deleted in any of the following cases even after the Member terminates the contract for usage.<br>１）Redisplayed in the form of storage or collection by others;<br>２）Form combined or linked with other’s Post;<br>３）Form in which the "Company" utilizes the member's posts<br><!--[if !supportEmptyParas]-->
<!--[endif]--><br><!--[if !supportEmptyParas]-->
<!--[endif]--><br>17. Limitation of Liability<br>① The "Company" is exempted from all liabilities and responsibilities in relation to the provision of Service if it is unable to provide the "Service" due to natural disasters or other equivalent force majeure.<br>② The "Company" is exempted from all liabilities and responsibilities for damages caused by unavoidable reasons such as maintenance, replacement, periodic inspection and construction of service facilities.<br>③ The "Company" is exempted from all liabilities and responsibilities for any loss is incurred due to the suspension of telecommunication service or failure to provide the telecommunication service in an ordinary manner by the relevant key telecommunications business operator<br>④ The Company shall not be liable for any disruption in the use of the Service due to the cause of the Member.<br>⑤ The "Company" shall not be liable for damages caused by user's computer error, or for any damage caused by user's insufficient personal information and e-mail address.<br>⑥ The "Company" shall not be held liable for the contents of the information, data, facts, credibility, accuracy, etc. posted by "member" in relation to the "service".<br>⑦ "Company" shall not be liable for any loss or loss of revenue that you expect to receive from the Service.<br>⑧ The Company shall not be liable or responsible for the User’s loss incurred due to materials received during the use of Service. Furthermore, the Company shall not be liable or responsible to compensate any mental or psychological damages of the User suffered due to the other User during the use of Service.<br>⑨ The "Company" shall be exempted from liability if it makes transactions through "Service" between "Members" or between "Members" and third parties.<br>⑩ The Company does not have any duty to intervene in any disputes occurred between the Users and between the User and third parties in relation to the Service, and the Company shall not be liable or responsible for any related or resulting losses.<br>⑪ The Company shall not be liable or responsible for any losses related to the use of Service that the Company provides to the User for free.<br>⑫ The “Member” is legally responsible for the mail or message content sent by "Member".<br><!--[if !supportEmptyParas]-->
<!--[endif]--><br><!--[if !supportEmptyParas]-->
<!--[endif]--><br>18. Governing Law and Jurisdiction<br>① Any lawsuit filed between "Company" and "Member" shall be governed by the laws of the Republic of Korea.<br>② In case of a dispute arising between "Company" and "Member", the court that has jurisdiction over the headquarters of the "Company" shall be the court of competent jurisdiction.
          </p>
          <a href="/main.do#contact" rel="nofollow" class="text__button">Go to homepage</a>
				</div>
			</div>
		</div>
	</section>

	<!-- jQuery -->
	<script src="/resources/js/libs/jquery.min.js"></script>
	<!-- smooth scroll -->
	<script src="/resources/js/libs/jquery.smooth-scroll.min.js"></script>

</body>
</html>